DROP SEQUENCE SEQ_TEST;
CREATE SEQUENCE SEQ_TEST
          START WITH 300
      INCREMENT BY     5
       MAXVALUE      310
       MINVALUE      290
          CYCLE
        NOCACHE;
        
SELECT SEQ_TEST.CURRVAL FROM DUAL;

SELECT SEQ_TEST.NEXTVAL FROM DUAL;

SELECT NVL(NULL, '0') FROM DUAL;

CREATE SEQUENCE SEQ_TEST CACHE 100;

INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL, '홍길동', 'M', 32);
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL, '김수정', 'F', 28);
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL, '박정길', 'M', 36);
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL, '박정길', 'M', 36);
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL, '박정길', 'M', 36);
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL, '박정길', 'M', 36);